version: '3.8'

services:
  db:
    image: postgres:14.9-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meeteevent-db
volumes:
  postgres-data:
