spring:
  jpa:
    hibernate:
      ddl-auto: update # this is not recommended on production, but it is done for presentation purposes
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

rsa:
  private-key: ${PRIVATE_KEY}
  public-key: ${PUBLIC_KEY}
