spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format.sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: prod

server:
  port: ${PORT:8080}
